version: "3"
services:

  nestjs:
    container_name: nestjs
    build:
      context: ./web-app/
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./web-app/.env.dev
    environment:
      - WAIT_HOSTS=postgres:5432
    ports:
      - 3000:3000
    volumes:
      - ./web-app/:/usr/app/

  postgres:
    container_name: postgres
    image: postgres:10.4
    restart: always
    env_file:
      - ./.docker/db/.env.db.dev
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    env_file:
      - ./.docker/pgadmin/.env.dev.pgadmin
    ports:
      - 8080:80
    depends_on:
      - postgres
