name: Admin app S3 deployment
on:
  push:
    branches:
      - deploy-admin-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Staging AWS

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install
        working-directory: ./admin-app
        run: yarn
      - name: Build
        working-directory: ./admin-app
        run: yarn build
      - name: Deploy on S3
        uses: reggionick/s3-deploy@v3
        with:
          folder: dir
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: us-east-1
